--- #YAML:1.0
name:               VOMS-Lite
version:            0.19
abstract:           Perl extension for VOMS Attribute certificate creation
author:
    - Mike Jones <mike.jones@manchester.ac.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::CBC:       0
    Crypt::DES:       0
    Crypt::DES_EDE3:  0
    Digest::MD2:      0
    Digest::MD5:      0
    Digest::SHA1:     0
    File::Copy:       0
    IO::Socket:       0
    IO::Socket::SSL:  0
    Math::BigInt:     0
    MIME::Base64:     0
    Sys::Hostname:    0
    Term::ReadKey:    0
    Time::Local:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
