--- #YAML:1.0
name:                VOMS-Lite
version:             0.09
abstract:            Perl extension for VOMS Attribute certificate creation
license:             ~
author:              
    - Mike Jones <mike.jones@manchester.ac.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::DES_EDE3:               0
    Digest::MD2:                   0
    Digest::MD5:                   0
    Digest::SHA1:                  0
    File::Copy:                    0
    IO::Socket:                    0
    IO::Socket::SSL:               0
    Math::BigInt:                  0
    MIME::Base64:                  0
    Regexp::Common:                0
    Sys::Hostname:                 0
    Term::ReadKey:                 0
    Time::Local:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
